# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'reckbo'
tagline:          'blog'
url:              http://reckbo.github.io/
paginate:         1
baseurl:          /
author:
  name:           Ryan Eckbo
  url:            https://twitter.com/reckbo
  #email:          
