# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'reckbo'
tagline:          'Blog'
url:              http://reckbo.github.io/
#paginate:         3
baseurl:          /
author:
  name:           Ryan Eckbo
  url:            http://reckbo.com
  #email:          
pages_list:       
  About: '/about'
  Archive: '/archive'
  Reading: '/reading'
  Github: 'http://github.com/reckbo'
  Bitbucket: 'http://bitbucket.org/reckbo'
  '@reckbo': 'http://twitter.com/reckbo' 
