# Permalinks
permalink:        pretty

# Setup
title:            'reckbo'
tagline:          'Blog'
url:              http://reckbo.github.io/
#paginate:         3
baseurl:          /
author:
  name:           Ryan Eckbo
  url:            http://reckbo.com
  #email:          
pages_list:       
  Home: '/'
  About: '/about'
  Archive: '/archive'
  Reading: '/reading'
highlighter: pygments
